[package]
authors = ["Michael Simpson <michael@wearethorn.org>"]
edition = "2018"
name = "cyclops"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
gpu = ["faiss/gpu"]

[dependencies]
faiss = {version = "0.9.0"}
ndarray = "0.14.0"
opencv = {version = "0.49", features = ["contrib"]}
