[package]
authors = ["Michael Simpson <michael@wearethorn.org>"]
edition = "2018"
name = "cyclops-cli"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
cyclops = {path = "../cyclops"}
